---
addons:
  apt:
    packages:
      - aspell
      - aspell-en
language: perl
perl:
  - dev
  - "blead"
  - "blead-thr"
  - "5.30"
  - "5.28"
  - "5.28-thr"
  - "5.26"
  - "5.26-thr"
  - "5.24"
  - "5.24-thr"
  - "5.22"
  - "5.22-thr"
  - "5.20"
  - "5.20-thr"
  - "5.18"
  - "5.18-thr"
  - "5.16"
  - "5.16-thr"
  - "5.14"
  - "5.14-thr"
  - "5.12"
  - "5.12-thr"
  - "5.10"
  - "5.10-thr"
  - "5.8"
  - "5.8-thr"
cache:
  directories:
    - $HOME/perl5
matrix:
  allow_failures:
    - perl: blead
    - perl: blead-thr
    - env: LIVE_JIGSAW_TESTS=1
  fast_finish: 1
  include:
    - env: COVERAGE=1
      perl: "5.30"
    - env: LIVE_JIGSAW_TESTS=1
      perl: "5.30"
env:
  global:
    - AUTHOR_TESTING=1
    - AUTOMATED_TESTING=1
    - RELEASE_TESTING=1
    - PERL_CPANM_OPT=--with-suggests
    - SENDMAIL=/usr/sbin/sendmail  # fake, but needed for LWP::Protocol::mailto
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR             # $BUILD_DIR is set by the build-dist command
install:
  - cpan-install Data::Dump Authen::NTLM Test::Spelling Test::Pod Test::Pod::Coverage Test::Version Test::EOL
  - cpan-install --deps       # installs prereqs, including optional modules
  - cpan-install --coverage   # installs converage prereqs, if enabled
before_script:
  - coverage-setup
script:
  - perl Makefile.PL
  - make
  - prove -b -r -s -j$(test-jobs) $(test-files)
after_success:
  - coverage-report
### __app_cisetup__
# ---
# force_threaded_perls: 0
# perl_caching: 1

### __app_cisetup__
