language: perl
perl:
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"
  - "5.12"
  - "5.10"
  - "5.8"
env:
  - "HARNESS_OPTIONS=j9"
install:
  - "cpanm -n Test::More Test::Pod Test::Pod::Coverage"
  - "cpanm -n --installdeps ."
sudo: false
notifications:
  email: false
