#!/local/bin/perl

# $Id: install-lwp,v 1.5 1995/07/16 07:20:09 aas Exp $
#
# This script might be used to install LWP
#

require 5.001;

#
# Check that URI::URL is installed
#

eval {
    require URI::URL;
};
if ($@) {
    die "You need to install the URI::URL module before you install LWP.\n";
} else {
    $version = $URI::URL::Version || $URI::URL::VERSION;
    print "You have installed URI::URL version $version.\n";
    if ($URI::URL::VERSION < 3.00) {
        die "Please upgrade URI::URL, LWP needs at least version 3.00.\n";
    } else {
        # print "That's just what I need!\n";
    }
}

#
# Find some suitable place to install LWP
#
use Config;
@loc = (
   $Config{'installsitelib'},
   $Config{'installprivlib'},
);

for $dir (@loc) {
    next unless length $dir;
    next unless -d $dir;
    print "Install LWP in $dir? [n] ";
    chomp($ans = <STDIN>);
    if ($ans =~ /^y(es)?$/i) {
        install($dir);
        last;
    }
}

unless ($installed) {
  MANUAL:
    {
        print "Enter directory where you want to install LWP\n";
        print "> ";
        chomp($dir = <STDIN>);
        last unless length $dir;
        unless (-d $dir) {
            print "'$dir' is not a directory!\n";
            redo MANUAL;
        }
        install($dir);
    }
}

print <<"EOT" if $installed;

You may also want to install the scripts found in the 'bin' directory.
Edit the first line of the scripts to reflect the location of perl and
copy them to /usr/local/bin.

EOT
exit;


sub run
{
    print "Running: @_\n";
    system @_;
}

sub install
{
    my $dir = shift;
    if (-e "$dir/LWP") {
        die "$dir/LWP is in the way!\n" unless -d _;
        print "Overwriting old '$dir/LWP'...\n";
    }
    run "cp -r LWP* $dir";  # This is really all that need to be done
    $installed = 1;
}
