#!/local/perl/bin/perl -w

use LWP::UserAgent;

$ua = new LWP::UserAgent;

$req = new HTTP::Request GET => 'ftp://ftp.uit.no/';
$req->header(Accept => "text/html");

$res  = $ua->request($req);

print $res->as_string;

